name: 🧪 Playwright Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # if you need to pass env vars/use .env secrets
      BASE_URL: ${{ secrets.BASE_URL }}
      PDS_USER: ${{ secrets.PDS_USER }}
      PDS_PASS: ${{ secrets.PDS_PASS }}
    steps:
      # Step 1: Check out the code
      - name: Checkout repo
        uses: actions/checkout@v4
      # Step 2: Set up Node.js
      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      # Step 4: Install Playwright and browsers
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      # Step 5: Run Playwright tests
      - name: Run Playwright tests
        run: |
          npx playwright test \
            --config=playwright.config.ts \
            --workers=50% \
            --reporter=list,html
      # Step 6: Upload Playwright test report (HTML or other)
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: playwright-videos
          path: test-results/**/*.webm
      - name: Upload traces
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/**/*.zip
